{% set name = "interface_meta" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6abcf78d27e695b157f44f226ff955ff766d43e8dbd6bd1d763c3e2a99beb4f2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
    - poetry-dynamic-versioning
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - interface_meta
    - interface_meta.utils

about:
  home: https://github.com/matthewwardrop/interface_meta
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: '`interface_meta` provides a convenient way to expose an extensible API with enforced method signatures and consistent documentation.'
  doc_url: https://github.com/matthewwardrop/interface_meta
  dev_url: https://github.com/matthewwardrop/interface_meta

extra:
  recipe-maintainers:
    - matthewwardrop
